
/*This script has been, partially or completely, generated by the GenerateVariableWindow*/
using UnityEditor;
using UnityEngine;

namespace LoGaCulture.LUTE
{
    [CustomPropertyDrawer(typeof(DaylightCycleData))]
    public class DaylightCycleDataDrawer : VariableDataDrawer<DaylightCycleVariable>
    { }
}