
/*This script has been, partially or completely, generated by the GenerateVariableWindow*/
using UnityEditor;
using UnityEngine;

namespace LoGaCulture.LUTE
{
    [CustomPropertyDrawer(typeof(UDateData))]
    public class UDateDataDrawer : VariableDataDrawer<UDateVariable>
    { }
}