
/*This script has been, partially or completely, generated by the GenerateVariableWindow*/
using UnityEngine;
using LoGaCulture.LUTE;

namespace LoGaCulture.LUTE
{
    /// <summary>
    /// DaylightCycle variable type.
    /// </summary>
    [VariableInfo("Date Time", "DaylightCycle")]
    [AddComponentMenu("")]
	[System.Serializable]
	public class DaylightCycleVariable : BaseVariable<LoGaCulture.LUTE.DaylightCycle>
	{ }

	/// <summary>
	/// Container for a DaylightCycle variable reference or constant value.
	/// </summary>
	[System.Serializable]
	public struct DaylightCycleData
	{
		[SerializeField]
		[VariableProperty("<Value>", typeof(DaylightCycleVariable))]
		public DaylightCycleVariable daylightCycleRef;

		[SerializeField]
		public LoGaCulture.LUTE.DaylightCycle daylightCycleVal;

		public static implicit operator LoGaCulture.LUTE.DaylightCycle(DaylightCycleData DaylightCycleData)
		{
			return DaylightCycleData.Value;
		}

		public DaylightCycleData(LoGaCulture.LUTE.DaylightCycle v)
		{
			daylightCycleVal = v;
			daylightCycleRef = null;
		}

		public LoGaCulture.LUTE.DaylightCycle Value
		{
			get { return (daylightCycleRef == null) ? daylightCycleVal : daylightCycleRef.Value; }
			set { if (daylightCycleRef == null) { daylightCycleVal = value; } else { daylightCycleRef.Value = value; } }
		}

		public string GetDescription()
		{
			if (daylightCycleRef == null)
			{
				return daylightCycleVal.ToString();
			}
			else
			{
				return daylightCycleRef.Key;
			}
		}
	}
}