
/*This script has been, partially or completely, generated by the GenerateVariableWindow*/
using UnityEngine;


namespace LoGaCulture.LUTE
{
    /// <summary>
    /// Sprite variable type.
    /// </summary>
    [VariableInfo("Other", "Sprite")]
    [AddComponentMenu("")]
	[System.Serializable]
	public class SpriteVariable : BaseVariable<UnityEngine.Sprite>
	{ }

	/// <summary>
	/// Container for a Sprite variable reference or constant value.
	/// </summary>
	[System.Serializable]
	public struct SpriteData
	{
		[SerializeField]
		[VariableProperty("<Value>", typeof(SpriteVariable))]
		public SpriteVariable spriteRef;

		[SerializeField]
		public UnityEngine.Sprite spriteVal;

		public static implicit operator UnityEngine.Sprite(SpriteData SpriteData)
		{
			return SpriteData.Value;
		}

		public SpriteData(UnityEngine.Sprite v)
		{
			spriteVal = v;
			spriteRef = null;
		}

		public UnityEngine.Sprite Value
		{
			get { return (spriteRef == null) ? spriteVal : spriteRef.Value; }
			set { if (spriteRef == null) { spriteVal = value; } else { spriteRef.Value = value; } }
		}

		public string GetDescription()
		{
			if (spriteRef == null)
			{
				return spriteVal.ToString();
			}
			else
			{
				return spriteRef.Key;
			}
		}
	}
}