
/*This script has been, partially or completely, generated by the GenerateVariableWindow*/
using UnityEngine;

namespace LoGaCulture.LUTE
{
    /// <summary>
    /// UDateTime variable type.
    /// </summary>
    [VariableInfo("Date Time", "UDateTime")]
    [AddComponentMenu("")]
    [System.Serializable]
    public class UDateTimeVariable : BaseVariable<UDateTime>
    { }

    /// <summary>
    /// Container for a UDateTime variable reference or constant value.
    /// </summary>
    [System.Serializable]
    public struct UDateTimeData
    {
        [SerializeField]
        [VariableProperty("<Value>", typeof(UDateTimeVariable))]
        public UDateTimeVariable uDateTimeRef;

        [SerializeField]
        public UDateTime uDateTimeVal;

        public static implicit operator UDateTime(UDateTimeData UDateTimeData)
        {
            return UDateTimeData.Value;
        }

        public UDateTimeData(UDateTime v)
        {
            uDateTimeVal = v;
            uDateTimeRef = null;
        }

        public UDateTime Value
        {
            get { return (uDateTimeRef == null) ? uDateTimeVal : uDateTimeRef.Value; }
            set { if (uDateTimeRef == null) { uDateTimeVal = value; } else { uDateTimeRef.Value = value; } }
        }

        public string GetDescription()
        {
            if (uDateTimeRef == null)
            {
                return uDateTimeVal.ToString();
            }
            else
            {
                return uDateTimeRef.Key;
            }
        }
    }
}